-- https://school.programmers.co.kr/learn/courses/30/lessons/273710

SELECT A.ITEM_ID, A.ITEM_NAME
FROM ITEM_INFO AS A
INNER JOIN ITEM_TREE AS B
ON A.ITEM_ID = B.ITEM_ID
WHERE B.PARENT_ITEM_ID IS NULL