-- https://school.programmers.co.kr/learn/courses/30/lessons/299308

SELECT
    CONCAT(CEIL(MONTH(DIFFERENTIATION_DATE) / 3), 'Q') AS QUARTER
    , COUNT(ID) ECOLI_COUNT
FROM ECOLI_DATA
GROUP BY CONCAT(CEIL(MONTH(DIFFERENTIATION_DATE) / 3), 'Q')
ORDER BY QUARTER