-- https://school.programmers.co.kr/learn/courses/30/lessons/133026

SELECT B.INGREDIENT_TYPE, SUM(A.TOTAL_ORDER) AS TOTAL_ORDER
FROM ICECREAM_INFO AS B
INNER JOIN FIRST_HALF AS A
ON B.FLAVOR = A.FLAVOR
GROUP BY B.INGREDIENT_TYPE
ORDER BY TOTAL_ORDER

