SELECT * FROM (
    SELECT CASE 
        WHEN (SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY LIKE 'Front%' )) > 0
            AND (SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'Python')) > 0
        THEN 'A'
        WHEN (SKILL_CODE & (SELECT CODE FROM SKILLCODES WHERE NAME = 'C#')) > 0
        THEN 'B'
        WHEN (SKILL_CODE & (SELECT SUM(CODE) FROM SKILLCODES WHERE CATEGORY LIKE 'Front%')) > 0
        THEN 'C'
        ELSE NULL
    END AS GRADE, 
    ID,
    EMAIL
FROM DEVELOPERS 
) AS t
WHERE GRADE IS NOT NULL
ORDER BY GRADE, ID