-- https://school.programmers.co.kr/learn/courses/30/lessons/151141


WITH VALUE AS (
    SELECT C.DAILY_FEE, C.CAR_TYPE, H.HISTORY_ID, 
    DATEDIFF(H.END_DATE, H.START_DATE) + 1 AS PERIOD,
    CASE 
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 7 THEN NULL
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 30 THEN '7일 이상'
        WHEN DATEDIFF(H.END_DATE, H.START_DATE) + 1 < 90 THEN '30일 이상'
        ELSE '90일 이상'
    END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    INNER JOIN CAR_RENTAL_COMPANY_CAR AS C
    ON C.CAR_ID = H.CAR_ID
    WHERE C.CAR_TYPE = '트럭'
)

SELECT 
    VALUE.HISTORY_ID, 
    ROUND(VALUE.DAILY_FEE * VALUE.PERIOD * (100 - IFNULL(P.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM VALUE
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
-- 할인율은 CAR_TYPE과 DURATION_TYPE 조합에 따라 다름
ON VALUE.DURATION_TYPE = P.DURATION_TYPE AND VALUE.CAR_TYPE = P.CAR_TYPE
ORDER BY FEE DESC, VALUE.HISTORY_ID DESC
