-- https://school.programmers.co.kr/learn/courses/30/lessons/144856

SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, SUM((S.SALES * B.PRICE)) AS TOTAL_SALES
FROM BOOK_SALES AS S
INNER JOIN BOOK AS B ON S.BOOK_ID = B.BOOK_ID
INNER JOIN AUTHOR AS A ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE YEAR(S.SALES_DATE) = 2022 AND MONTH(S.SALES_DATE) = 1
GROUP BY A.AUTHOR_ID, B.CATEGORY
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC


-- 💡 GROUP BY 사용 시 주의
-- SUM(S.SALES) * B.PRICE  안되는 이유
-- GROUP BY에 BOOK_ID가 없으므로, B.PRICE는 여러 개 중에 어떤거 선택될지 모름
-- GROUP BY에 없는 열을 SELECT하거나 계산에 사용하면 잘못된 값이 나올 수도 있음