SELECT SUM(SCORE) AS SCORE, EMP_NO, EMP_NAME, POSITION, EMAIL 
FROM HR_GRADE 
INNER JOIN HR_EMPLOYEES 
USING (EMP_NO) 
GROUP BY EMP_NO, EMP_NAME, POSITION, EMAIL 
ORDER BY SCORE DESC 
LIMIT 1

-- 최대값을 가진 사원이 여러명인 경우 "인라인 뷰" 사용
SELECT SUM(SCORE) AS SCORE, EMP_NO, EMP_NAME, POSITION, EMAIL
FROM HR_EMPLOYEES
INNER JOIN HR_GRADE 
USING (EMP_NO)
GROUP BY EMP_NO, EMP_NAME, POSITION, EMAIL
HAVING SUM(SCORE) = (
    SELECT MAX(TOTAL_SCORE)
    FROM (
        SELECT SUM(SCORE) AS TOTAL_SCORE
        FROM HR_GRADE
        GROUP BY EMP_NO
    ) T
)
ORDER BY SCORE DESC
