-- https://school.programmers.co.kr/learn/courses/30/lessons/144855

SELECT B.CATEGORY, SUM(S.SALES) AS TOTAL_SALES
FROM BOOK_SALES AS S
INNER JOIN BOOK AS B
ON S.BOOK_ID = B.BOOK_ID
WHERE DATE_FORMAT(S.SALES_DATE, '%Y-%m-%d') LIKE '2022-01%'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY