-- https://school.programmers.co.kr/learn/courses/30/lessons/157339

SELECT 
C.CAR_ID, 
C.CAR_TYPE, 
FLOOR(C.DAILY_FEE * 30 * ((100 - P.DISCOUNT_RATE) / 100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS C
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS P
ON C.CAR_TYPE = P.CAR_TYPE
WHERE C.CAR_TYPE IN ('세단', 'SUV')
AND P.DURATION_TYPE = '30일 이상'
AND C.CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
)
AND FLOOR(C.DAILY_FEE * 30 * ((100 - P.DISCOUNT_RATE) / 100)) BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, C.CAR_TYPE ASC, CAR_ID DESC
